### ISSUE TITLE
NameError: name 'results_path' is not defined

### ISSUE THREAD

**Issue by asideras** [csqiangwen/DeepFillv2_Pytorch#17]
Hello,

after running `!bash ./run_test.sh `

I get :

`Traceback (most recent call last):
  File "/content/DeepFillv2_Pytorch/test.py", line 41, in <module>
    tester.WGAN_tester(opt)
  File "/content/DeepFillv2_Pytorch/tester.py", line 30, in WGAN_tester
    if not os.path.exists(results_path):
NameError: name 'results_path' is not defined`

**Comment by asideras** [comment]
results_path = opt.results_path  Add this in tester.py
